### ISSUE TITLE
No appimages on Ubuntu 20.04

### ISSUE THREAD

**Issue by PrzemekSkw** [vinifmor/bauh#145]
Hello, I install Bauh on Ubuntu with `pip install bauh`. I have all dependiences installed. I uninstall Appimage Launcher and reboot laptop. I run Bauh from command line:
```
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/home/lusia/.local/lib/python3.8/site-packages/bauh/gems/flatpak/flatpak.py", line 208, in read_updates
    update_id = '{}/{}/{}'.format(line_split[2], line_split[3], installation)
IndexError: list index out of range
```
```
$ python --version
Python 2.7.18
$ python3 --version
Python 3.8.5
```
There're only Flatpaks and Web apps in Bauh.

Regards,
Przemek

**Comment by vinifmor** [comment]
It seems to be a bug. I'm going to have a look here.  Regarding to AppImages, do you have **sqlite3** installed ? It's one of the required packages for AppImage support. Have a look at the [AppImage gem section](https://github.com/vinifmor/bauh#appimage-appimage) (there is a subtopic called **Required dependencies**).

**Comment by vinifmor** [comment]
Please, post here the results of the following commands:
- `flatpak --version`
- `flatpak update --user`
- `flatpak update --system` 

P.S: do not follow with these operations so we can check later if the fix is going to work on your end

**Comment by PrzemekSkw** [comment]
@vinifmor Hi, sorry for late answer.

```
$ flatpak --version
Flatpak 1.6.5

$ flatpak update --user
Wyszukiwanie aktualizacji…
Nie ma nic do zrobienia. [nothing to do]

$ flatpak update --system
Wyszukiwanie aktualizacji…
Informacja: org.gnome.Platform jest niewspierane z powodu: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Informacja: org.gnome.Platform.Locale jest niewspierane z powodu: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.


        Identyfikator                             Gałąź  Dz Repozytorium Pobieranie
 1.     com.github.muriloventuroso.easyssh.Locale stable u  flathub      < 333,1 kB (częściowo)
 2.     com.github.muriloventuroso.easyssh        stable u  flathub       < 20,6 MB

Kontynuować te zmiany w instalacji systemowej? [Y/n]: n
```
Regards.

**Comment by vinifmor** [comment]
@PrzemekSkw , I've pushed a possible fix on the staging branch. Could you give me a feedback if it does not crash anymore ?
```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
pip3 install .
```

**Comment by PrzemekSkw** [comment]
Hi, @vinifmor thanks it don't show any errors but still don't have appimages.
```
lusia@lusia-laptop:~$ git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
Cloning into 'bauh'...
remote: Enumerating objects: 376, done.
remote: Counting objects: 100% (376/376), done.
remote: Compressing objects: 100% (324/324), done.
remote: Total 376 (delta 89), reused 141 (delta 44), pack-reused 0
Receiving objects: 100% (376/376), 460.10 KiB | 1.51 MiB/s, done.
Resolving deltas: 100% (89/89), done.
lusia@lusia-laptop:~$ cd bauh/
lusia@lusia-laptop:~/bauh$ pip3 install .
Processing /home/lusia/bauh
Requirement already satisfied: colorama>=0.3.8 in /usr/lib/python3/dist-packages (from bauh==0.9.11) (0.4.3)
Requirement already satisfied: pyqt5>=5.12 in /usr/lib/python3/dist-packages (from bauh==0.9.11) (5.14.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from bauh==0.9.11) (2.7.3)
Requirement already satisfied: pyyaml>=3.13 in /usr/lib/python3/dist-packages (from bauh==0.9.11) (5.3.1)
Requirement already satisfied: requests>=2.18 in /usr/lib/python3/dist-packages (from bauh==0.9.11) (2.22.0)
Building wheels for collected packages: bauh
  Building wheel for bauh (setup.py) ... done
  Created wheel for bauh: filename=bauh-0.9.11-py3-none-any.whl size=574540 sha256=37204f1f02abfb63a82114c681214078126154a9ac69fe8c44fa0c78c5cb47fa
  Stored in directory: /tmp/pip-ephem-wheel-cache-lanwgsej/wheels/ef/4b/f1/1062c641bfe4146c4defebe76589ed658c1e6395c304db18dd
Successfully built bauh
Installing collected packages: bauh
Successfully installed bauh-0.9.11
lusia@lusia-laptop:~/bauh$ bauh
qt5ct: using qt5ct plugin
Unknown property letter-spacing
Unknown property letter-spacing
qt5ct: palette support is disabled
qt5ct: custom style sheet is disabled
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
Unknown property letter-spacing
```

Regards,
Przemek

**Comment by vinifmor** [comment]
@PrzemekSkw , is the AppImage type option displayed on the settings window ?

![bauh_settings](https://user-images.githubusercontent.com/4312414/102697818-8fd95c80-4217-11eb-90f0-477c6772b01d.png)

**Comment by PrzemekSkw** [comment]
@vinifmor as I said before I have only flatpak and web apps in Bauh. 
![Zrzut ekranu z 2020-12-19 22-39-39](https://user-images.githubusercontent.com/25219988/102700170-63d7ce80-424b-11eb-878d-b5d260241470.png)

**Comment by vinifmor** [comment]
Since the AppImage option does show up, you are probably missing the **sqlite3** dependency.

**Comment by PrzemekSkw** [comment]
@vinifmor Yes, that's it. I missed Appimage deps. Thanks You.
