### ISSUE TITLE
[flatpak] update sizes not being displayed when there are missing required runtimes to be installed

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#257]
![image](https://user-images.githubusercontent.com/11728067/162978580-daca6958-c5ef-4283-ba1a-eda17076d59f.png)

The upgrade went without a hitch, though.

At least for now, unless the mesa drivers screw me over after restarting. :D

**Comment by vinifmor** [comment]
I'll have a look. Thanks for reporting.

**Comment by vinifmor** [comment]
Flatpak does not print some of these Locales sizes. In relation to the others displayed, the sizes should have been displayed.  On my end it is working (tested with a default english locale and a different one)

Try the following:
1) Downgrade an app and a runtime (e.g: Mesa and LibreWolf)
2) Go to a terminal and  type: `LANG='' flatpak update` (but do not confirm the upgrade)
2.1) Check if the output displays the download sizes (paste here as well, please)
3) Try to upgrade the Flatpaks through bauh (use the staging version) and check if the sizes are displayed on the summary window

**Comment by Templayer** [comment]
No need to downgrade. I have a lot of software, it seems like.

![image](https://user-images.githubusercontent.com/11728067/163224424-f862f9dc-7aac-47ce-b374-d6bbeedcb0fb.png)

Also it looks like bauh isn't showing me a lot of updates - Epiphany, Ungoogled Chromium, Subtitle Composer...

```
jboksa1@JB-PC:~$ LANG='' flatpak update
Looking for updates?
Info: org.kde.Platform//5.12 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.kde.falkon
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Required runtime for org.gnome.Epiphany/x86_64/stable (runtime/org.gnome.Platform/x86_64/42) found in remote flathub
Do you want to install it? [Y/n]: Y


        ID                                          Branch     Op Remote  Download
 1.     com.github.Eloston.UngoogledChromium.Codecs stable     u  flathub   < 1,1?MB
 2.     org.freedesktop.Platform.Compat.i386        20.08      u  flathub < 153,4?MB
 3.     org.freedesktop.Platform.GL.default         20.08      u  flathub < 106,4?MB
 4.     org.freedesktop.Platform.GL32.default       20.08      u  flathub < 114,2?MB
 5.     org.freedesktop.Platform.Locale             20.08      u  flathub < 322,3?MB
 6.     org.freedesktop.Platform.Locale             21.08      u  flathub < 325,8?MB
 7.     org.freedesktop.Platform.ffmpeg-full        21.08      u  flathub   < 4,2?MB
 8.     org.gnome.Epiphany.Locale                   stable     u  flathub   < 2,3?MB
 9.     org.gnome.Platform.Locale                   40         u  flathub < 333,9?MB
10.     org.gnome.Platform.Locale                   41         u  flathub < 336,5?MB
11.     org.gnome.Platform.Locale                   42         i  flathub < 335,9?MB (partial)
12.     org.gnome.Platform                          42         i  flathub < 275,5?MB
13.     org.gnome.Epiphany                          stable     u  flathub  < 17,8?MB
14.     org.gnome.Platform                          41         u  flathub < 291,0?MB
15.     org.gnome.Platform                          40         u  flathub < 367,4?MB
16.     org.freedesktop.Platform                    21.08      u  flathub < 199,7?MB
17.     com.github.Eloston.UngoogledChromium        stable     u  flathub < 115,9?MB
18.     org.freedesktop.Platform                    20.08      u  flathub < 270,3?MB
19.     org.kde.Platform.Locale                     5.12       u  flathub < 334,3?MB (partial)
20.     org.kde.Platform                            5.12       u  flathub < 430,7?MB
21.     org.kde.Platform.Locale                     5.15-21.08 u  flathub < 345,3?MB
22.     org.kde.Platform                            5.15-21.08 u  flathub < 305,5?MB
23.     org.kde.subtitlecomposer.Locale             stable     u  flathub < 547,4?kB
24.     org.kde.subtitlecomposer                    stable     u  flathub  < 32,1?MB

Proceed with these changes to the system installation? [Y/n]: n

```

Updated to staging:

```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh
```

Inside the staging version:

![image](https://user-images.githubusercontent.com/11728067/163225603-85a02095-1722-447e-85a2-7c075f8a3b2b.png)

**Comment by Templayer** [comment]
Log with index out of bounds error was appended to the previous comment.

**Comment by Templayer** [comment]
> Using legacy 'setup.py install' for bauh, since package 'wheel' is not installed.

Umm... according to Debian apk package manager I do have it installed! Any ideas?

![image](https://user-images.githubusercontent.com/11728067/163226754-ffb442f4-1b2c-4bd0-ac20-87a3856e6298.png)

**Comment by Templayer** [comment]
I guess I have to add something to  this to enable wheel?

```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh
```

Even though that certainly isn't the root of the issue, we already have the stacktrace with an error... but it still bothers me. :D

**Comment by vinifmor** [comment]
I'm going to simulate some scenarios based on your output.

The staging has a fix for not displaying all updates (unfortunately, Flatpak command line interface was designed for humans, not for apps integration. Sometimes it displays unexpected warnings that break the output handling).

The **wheel** package is missing on the virtualenv. You can install it with the following command: `venv/bin/pip install wheel`

**Comment by vinifmor** [comment]
I've pushed a possible fix to the staging branch. Let me know if its working now.

**Comment by Templayer** [comment]
The index out of bounds error still appears (but I've noticed it appears when the main window is loaded. Previously, I thought it was created by the dialogue window without sizes)

```
Traceback (most recent call last):
  File "/home/jboksa1/bauh/venv/lib/python3.8/site-packages/bauh/gems/flatpak/flatpak.py", line 221, in read_updates
    update_id = f'{line_split[2]}/{line_split[3]}/{installation}/{line_split[5]}'
IndexError: list index out of range
```

The output is the same:

![image](https://user-images.githubusercontent.com/11728067/163333213-4586a50d-9636-42db-8c06-02c5484685be.png)

This is what I've called to get bauh staging running:

```
git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
cd bauh
python3 -m venv venv
venv/bin/pip install pip --upgrade
venv/bin/pip install setuptools --upgrade
venv/bin/pip install wheel
venv/bin/pip install -r requirements.txt
venv/bin/pip install .
venv/bin/bauh
```

There is a not so old Czech proverb that I believe applies here: Finishing up the last 5% of a (coding) project takes more time than the previous 95%.

**Comment by vinifmor** [comment]
I believe for some reason you are not installing the current staging. Look at line error on the master and staging branches:
- master: https://github.com/vinifmor/bauh/blob/master/bauh/gems/flatpak/flatpak.py#L221
- staging: https://github.com/vinifmor/bauh/blob/staging/bauh/gems/flatpak/flatpak.py#L221

Please, try installing the latest staging archive with pip: https://github.com/vinifmor/bauh/archive/aff72e0f82895eefb2b3fb97b7036efa4075183d.tar.gz

**Comment by Templayer** [comment]
I've looked into it - the first line fails for me, so I need to update my bash script:

jboksa1@JB-PC:~$ git clone https://github.com/vinifmor/bauh.git -b staging --depth=1
fatal: destination path 'bauh' already exists and is not an empty directory.

**Comment by Templayer** [comment]
Unfortunately I'm not proficient in using git via commandline. I know I need to pull a never staging version, but I don't know what  `-b staging --depth=1` means and how to translate it into a pull command.

**Comment by vinifmor** [comment]
You can add a remove command as the first line (e.g: `rm -rf bauh`) to your script. But installing the archive from the link with pip will do trick as well.

**Comment by Templayer** [comment]
I know that installing it from a specific link will do the trick, but I need to have it a little bit more streamlined.

I just have a launcher that launches a bash script. So I can just double click it and launch a test/staging version. Eventually, that is. Can't always count on you giving me the newest staging package, as that link keeps changing.

**Comment by vinifmor** [comment]
Sure. I just want to know if the issue has been fixed.

**Comment by Templayer** [comment]
I can't test it right now, as there are holidays in the Czech Republic.

I'll test it on Tuesday.

**Comment by Templayer** [comment]
Tried it with 0.10.3 Staging, got a "?":

![image](https://user-images.githubusercontent.com/11728067/163943506-5c9f7fa6-0e28-46d0-a4a7-16c247d50ea2.png)

By the way, not having a "check all" functionality is getting REALLY tedious now:

![image](https://user-images.githubusercontent.com/11728067/163943346-d168c4a7-bccb-440e-8633-f923f796f78e.png)

Terminal doesn't give an error:

> Successfully built bauh
> Installing collected packages: bauh
> Successfully installed bauh-0.10.3
>

**Comment by Templayer** [comment]
```
jboksa1@JB-PC:~$ LANG='' flatpak update
Looking for updates?
Info: org.kde.Platform//5.12 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.kde.falkon
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
Required runtime for org.gnome.Epiphany/x86_64/stable (runtime/org.gnome.Platform/x86_64/42) found in remote flathub
Do you want to install it? [Y/n]: Y

New com.github.micahflee.torbrowser-launcher permissions:
    fallback-x11      wayland      dbus access [1]

    [1] org.kde.kconfig.notify


        ID                                          Branch     Op Remote  Download
 1.     com.github.Eloston.UngoogledChromium.Codecs stable     u  flathub   < 1,1?MB
 2.     org.freedesktop.Platform.Compat.i386        20.08      u  flathub < 153,4?MB
 3.     org.freedesktop.Platform.GL.default         20.08      u  flathub < 106,4?MB
 4.     org.freedesktop.Platform.GL32.default       20.08      u  flathub < 114,2?MB
 5.     org.freedesktop.Platform.Locale             20.08      u  flathub < 322,3?MB
 6.     org.freedesktop.Platform.Locale             21.08      u  flathub < 325,8?MB
 7.     org.freedesktop.Platform.ffmpeg-full        21.08      u  flathub   < 4,2?MB
 8.     org.gnome.Epiphany.Locale                   stable     u  flathub   < 2,3?MB
 9.     org.gnome.Platform.Locale                   40         u  flathub < 333,9?MB
10.     org.gnome.Platform.Locale                   41         u  flathub < 336,5?MB
11.     org.gnome.Platform.Locale                   42         i  flathub < 335,9?MB (partial)
12.     org.gnome.Platform                          42         i  flathub < 275,5?MB
13.     org.gnome.Epiphany                          stable     u  flathub  < 17,8?MB
14.     org.gnome.Platform                          41         u  flathub < 291,0?MB
15.     org.gnome.Platform                          40         u  flathub < 367,4?MB
16.     org.freedesktop.Platform                    21.08      u  flathub < 199,7?MB
17.     com.github.Eloston.UngoogledChromium        stable     u  flathub < 115,9?MB
18.     org.freedesktop.Platform                    20.08      u  flathub < 270,3?MB
19.     org.kde.Platform.Locale                     5.12       u  flathub < 334,3?MB (partial)
20.     org.kde.Platform                            5.12       u  flathub < 430,7?MB
21.     org.kde.Platform.Locale                     5.15-21.08 u  flathub < 345,3?MB
22.     org.kde.Platform                            5.15-21.08 u  flathub < 305,5?MB
23.     com.github.micahflee.torbrowser-launcher    stable     u  flathub   < 8,7?MB
24.     org.kde.subtitlecomposer.Locale             stable     u  flathub < 547,4?kB
25.     org.kde.subtitlecomposer                    stable     u  flathub  < 32,1?MB

Proceed with these changes to the system installation? [Y/n]: n

```

**Comment by Templayer** [comment]
```
LANG='' flatpak update --no-deps
Looking for updates?
Info: org.kde.Platform//5.12 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Applications using this runtime:
   org.kde.falkon
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs//18.08 is end-of-life, with reason:
   The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.


        ID                              Branch     Op Remote  Download
 1.     org.freedesktop.Platform.Locale 20.08      u  flathub < 322,3?MB
 2.     org.freedesktop.Platform.Locale 21.08      u  flathub < 325,8?MB
 3.     org.gnome.Epiphany.Locale       stable     u  flathub   < 2,3?MB
 4.     org.gnome.Platform.Locale       40         u  flathub < 333,9?MB
 5.     org.gnome.Platform.Locale       41         u  flathub < 336,5?MB
 6.     org.kde.Platform.Locale         5.15-21.08 u  flathub < 345,3?MB
 7.     org.kde.subtitlecomposer.Locale stable     u  flathub < 547,4?kB

```

**Comment by vinifmor** [comment]
I've tried to reproduce this with Linux Mint, but it is working fine on my end (for both Flatpak and Debian). 

![bauh_debian_upgrade](https://user-images.githubusercontent.com/4312414/171920580-e7616894-685c-49c5-bdf1-ad56b82a9056.png)

I'm going to try more scenarios here.

**Comment by Templayer** [comment]
> I've tried to reproduce this with Linux Mint, but it is working fine on my end (for both Flatpak and Debian).
> 
> ![bauh_debian_upgrade](https://user-images.githubusercontent.com/4312414/171920580-e7616894-685c-49c5-bdf1-ad56b82a9056.png)
> 
> I'm going to try more scenarios here.

Did you try getting it running in the Czech locale? We should figure out if that is the culprit or not...furthermore, if you DO manage to duplicate it, you can step in and debug it.
