### ISSUE TITLE
Bottom-cut version strings + the window is too big and cannot be made smaller (version string differences are too long)

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#261]
I'm using 0.10.3 staging, and the strings for version changes have their bottoms cut.

![image](https://user-images.githubusercontent.com/11728067/163942045-68db4345-81b0-4c36-9f2c-fe0d7f95b1a9.png)

Another problem - some of the version strings are too long - I'm on a 2K screen and I cannot make the window smaller due to the size of the libsmbclient and libwbclient0 package version changes.

It doesn't even fit my laptop monitor now:

![image](https://user-images.githubusercontent.com/11728067/163942887-3c2e6e55-8801-49b3-b743-fd10ac3c9db8.png)

A nice solution would be to set a maximum (and possibly let the user set the maximum by dragging the column header borders, which is pretty much standard in Windows...) and if the string is bigger, make the item in the list have a multi-row span (if possible).

**Comment by Templayer** [comment]
Even GitHub goes the "multiple rows" route:

![image](https://user-images.githubusercontent.com/11728067/163944377-1db06176-62af-4fab-9b89-a76a977c6024.png)

**Comment by vinifmor** [comment]
Are you using any of bauh's scaling properties (available on the interface settings) ? Is this happening with 0.10.2 ? (because I've recently pushed some changes related to the UI resizing on the staging branch).

**Comment by Templayer** [comment]
It's happening only on 0.10.3 Staging. Settings:

![image](https://user-images.githubusercontent.com/11728067/164171625-75bf46f5-0c6c-46b1-9ffa-601b0896e697.png)

Minimum width is also enforced in 0.10.2, but everything is smaller with identical settings:

![image](https://user-images.githubusercontent.com/11728067/164171978-d919c32d-5427-42dc-8e4e-7454e7d55a84.png)

**Comment by Templayer** [comment]
You know what they say. The last 5% of a coding project takes more time than the previous 95%. :D

**Comment by vinifmor** [comment]
It might be related to the height changes. I'm going to test some scenarios here.

**Comment by vinifmor** [comment]
@Templayer, I'm still not able to reproduce this issue. 

Does your desktop environment have a different global scale ? What DPI are you currently using ?

**Comment by Templayer** [comment]
Nope, UI scaling is set to 1x. "Měřítko zobrazení uživatelského rozhraní" is the option.

Work monitor:
![image](https://user-images.githubusercontent.com/11728067/167355842-a3bdc010-2707-4e5c-9741-c5dd1404d661.png)

Internal laptop monitor:
![image](https://user-images.githubusercontent.com/11728067/167355906-335fcf8b-3875-4665-9f01-bbc56a9deef5.png)

As for the DPI in Cinnamon: "The DPI value of 96x96 appears to be fixed."
Source: https://forums.linuxmint.com/viewtopic.php?t=226198

That somewhat sucks, but on the other hand, I've only used DPI settings in Windows to make the UI larger. If I can make the UI larger without affecting DPI, then I have no need of changing DPI, so I'm going to have mercy with Cinnamon on this one. :D

**Comment by vinifmor** [comment]
Thanks for sharing this. I'm going to test more scenarios here.

**Comment by Templayer** [comment]
And thanks for doing this for us. We appreciate it.

Dealing with these issues must be very frustrating.

**Comment by vinifmor** [comment]
No worries. The problem is that I currently don't have a display device that supports HDPI resolutions to confirm the issue has been fixed. I will probably rollback some changes since you said this doesn't happen with 0.10.2.

**Comment by Templayer** [comment]
I have quite a few pieces of software available - besides the integrated screen and the HP screen, I do also have a big 32" Samsung 2K screen at home (and also a 1600x1050 old Samsung screen, but I'm not sure how hard it would be to connect it, as it is a DVI and my laptop with Linux only has HDMI, but I think I have an adapter somewhere). And a shitty television.

**Comment by Templayer** [comment]
The issue persists on my work HP screen and my internal laptop monitor:

![image](https://user-images.githubusercontent.com/11728067/169319384-3ef98611-3c76-48af-85a5-c0897f02e750.png)

I cannot ascertain if the "version changes that are too long can make the application window not fit the screen and force that as a minimum size, thus it cannot be made smaller to fit the screen" issue persists, as the version changes strings currently available are not long enough to test that problem out.

**Comment by vinifmor** [comment]
Question: the issue happens on you primary screen ? Because the interface sizing is based on the primary screen.

**Comment by Templayer** [comment]
Um... both screens have an independent interface sizing option. If it was always based on the primary screen, wouldn't it be greyed out / not available in the options for the secondary screen?

Also, both have interface sizing set at 1x.

I'll try launching the staging version with the HP screen disconnected if there is any change tomorrow.

**Comment by Templayer** [comment]
As expected, there is no change when disconnecting the primary screen and launching the staging version afterwards. Interface sizing set to 1x on internal (usually non-primary) screen:

![image](https://user-images.githubusercontent.com/11728067/169488605-84d0adc1-2f8e-4658-aa16-a064ee2d3c66.png)

It's particularly easy to notice when reading "dfsg", because the "g" is all f*cked up.

**Comment by vinifmor** [comment]
I've installed a clean Linux Mint 20.0.3 Cinnamon virtual machine at 1080p and couldn't reproduce the issue. Also tested with a 720p with no issue.

![bauh_cinnamon_1080p](https://user-images.githubusercontent.com/4312414/169539025-e019751b-a32e-4b80-803c-97dc851d22d5.png)

Have you tweaked any Qt settings ?

On the system's display settings:  does changing the scaling to "normal" instead of "1x" fix the issue ?

Could you share your system environment variables through a compressed tar.gz file ?

**Comment by Templayer** [comment]
With any other display other than the integrated one disconnected, I have changed it to normal (didn't even know there was a choice like that there beforehand). And then I've removed staging and got staging again to make sure (because I have no idea what would or wouldn't happen if I left bauh running).
No change.
Then I tried disabling HiDPI in bauh settings, but nothing changed. I have switched from Fusion to the Windows style in the bauh settings. No change. I tried different themes, but nope.

How do I tweak Qt settings? :D  

As far as the system environment variables go, is this enough? It isn't long enough to warrant me compressing it, at least this specific output doesn't seem to be (or do you want it as files? Which ones?):

```
jboksa1@JB-PC:~$ printenv
SHELL=/bin/bash
SESSION_MANAGER=local/JB-PC:@/tmp/.ICE-unix/1836,unix/JB-PC:/tmp/.ICE-unix/1836
QT_ACCESSIBILITY=1
COLORTERM=truecolor
XDG_CONFIG_DIRS=/etc/xdg/xdg-cinnamon2d:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
DERBY_HOME=/usr/lib/jvm/jdk1.8.0_311/db
LANGUAGE=cs_CZ:cs
MANDATORY_PATH=/usr/share/gconf/cinnamon2d.mandatory.path
LC_ADDRESS=cs_CZ.UTF-8
JAVA_HOME=/usr/lib/jvm/jdk1.8.0_311
LC_NAME=cs_CZ.UTF-8
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
DOTNET_CLI_TELEMETRY_OPTOUT=true
CINNAMON_VERSION=5.2.7
DESKTOP_SESSION=cinnamon2d
LC_MONETARY=cs_CZ.UTF-8
SSH_AGENT_PID=1919
GTK_MODULES=gail:atk-bridge
XDG_SEAT=seat0
PWD=/home/jboksa1
XDG_SESSION_DESKTOP=cinnamon2d
LOGNAME=jboksa1
QT_QPA_PLATFORMTHEME=qt5ct
XDG_SESSION_TYPE=x11
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
XAUTHORITY=/home/jboksa1/.Xauthority
J2REDIR=/usr/lib/jvm/jdk1.8.0_311/jre
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/jboksa1
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GDM_LANG=cs
HOME=/home/jboksa1
LC_PAPER=cs_CZ.UTF-8
LANG=cs_CZ.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
XDG_CURRENT_DESKTOP=X-Cinnamon
VTE_VERSION=6003
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/e55d4b1b_1741_4f48_8e80_ccd6b25a882a
GJS_DEBUG_OUTPUT=stderr
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_SESSION_CLASS=user
TERM=xterm-256color
LC_IDENTIFICATION=cs_CZ.UTF-8
GTK_OVERLAY_SCROLLING=1
DEFAULTS_PATH=/usr/share/gconf/cinnamon2d.default.path
J2SDKDIR=/usr/lib/jvm/jdk1.8.0_311
LESSOPEN=| /usr/bin/lesspipe %s
USER=jboksa1
GNOME_TERMINAL_SERVICE=:1.184
DISPLAY=:0
SHLVL=1
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
XDG_VTNR=7
XDG_SESSION_ID=c1
XDG_RUNTIME_DIR=/run/user/1000
LC_TIME=cs_CZ.UTF-8
GTK3_MODULES=xapp-gtk3-module
XDG_DATA_DIRS=/usr/share/cinnamon2d:/usr/share/gnome:/home/jboksa1/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
PATH=/home/jboksa1/.local/bin:/home/jboksa1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/jdk1.8.0_311/bin:/usr/lib/jvm/jdk1.8.0_311/db/bin:/usr/lib/jvm/jdk1.8.0_311/jre/bin:/home/jboksa1/.dotnet/tools
GDMSESSION=cinnamon2d
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
LC_NUMERIC=cs_CZ.UTF-8
_=/usr/bin/printenv
```

**Comment by Templayer** [comment]
I just encountered a little different bug, but I haven't tried it in staging (or tried what you have suggested - I'll take a look at that later, but I need to report this now while I can, as I am going to update the packages that allow me to show this to you).

In the following printscreen, how do I get to the item actions part (like the "do not update" checkbox) at the rightmost columns?

![image](https://user-images.githubusercontent.com/11728067/170842124-3e4be769-02ea-4ac7-aaca-e203a2faeba0.png)

There is no horizontal scrollbar. It looks like the version differences string broke the GUI (which is something I have partially already reported in this issue - the version string being too long and without limits).

**Comment by Templayer** [comment]
Also, (and completely offtopic) I've just updated my Linux kernel/firmware/whatever by using bauh for the first time. If I do not return, it is totally your fault. :D :D :D xD

[upgrade_2022528_1653771127.log](https://github.com/vinifmor/bauh/files/8791876/upgrade_2022528_1653771127.log)

**Comment by vinifmor** [comment]
There is a fix on the staging branch that prevents bauh from fully stretching beyond the primary screen limits.

P.S: relax about the upgrade. bauh upgrades my kernel every week  :) (you have to worry if there are issues with the back-end itself. In your case: aptitude)

**Comment by Templayer** [comment]
> There is a fix on the staging branch that prevents bauh from fully stretching beyond the primary screen limits.

> In the following printscreen, how do I get to the item actions part (like the "do not update" checkbox) at the rightmost columns?
> 
> ![image](https://user-images.githubusercontent.com/11728067/170842124-3e4be769-02ea-4ac7-aaca-e203a2faeba0.png)


That won't solve this problem / specific variant, I think? Granted, that isn't the problem this Issue was created in mind with.

But yeah, I've been sick ever since Tuesday last week and I still am, so it's hard for me to force myself to do ANYTHING.

**Comment by Templayer** [comment]
This is the current state - I don't have an app with a version change that would be long enough to test it:

![image](https://user-images.githubusercontent.com/11728067/171444303-d9e6b0e5-b954-475f-9962-bf7c7c307ecb.png)

**Comment by vinifmor** [comment]
Ok... I'll check if the table row has a property to preventing this cutting. Thank you for the feedback.
